### PR TITLE
ALF-22013 Fix UTF-8 as default locale

### PR DESCRIPTION
**Pull request by angelborroy-ks**
Suggestion to set UTF-8 as default locale.

### CODE REVIEW

**Comment by derekhulley** [comment]
For reference: https://issues.alfresco.com/jira/browse/DEPLOY-454

**Comment by rgauss** [comment]
Apologies for the delay, and thanks for the suggestion.

We'll be taking a closer look at this in the near future.

**Comment by nicdoye** [comment]
I've written some comments in https://issues.alfresco.com/jira/browse/DEPLOY-546 . I'll double check with the other teams, then apply.

**Comment by killerboot** [comment]
Shouldn't we use builtin localectl instead?
Something like:
`localectl set-locale LANG=en_US.utf8`

**Comment by nicdoye** [comment]
`localectl` talks to `systemd-localed` which isn't running in the container.

**Comment by killerboot** [comment]
@nicdoye right, thanks for clarification.

**Comment by nicdoye** [comment]
I'm all for doing things "the right way"™, so please keep bringing up suggestions like this.

**Comment by nicdoye** [comment]
Many thanks @angelborroy-ks and sorry for the delay

**Pull request merged**
