### PR TITLE
DEPLOY-574 Support Java 11 in addition to Java 8

### PR DESCRIPTION
**Pull request by nicdoye**
Support building multiple images based off different versions of Java (via `ARG JAVA_PKG` added in DEPLOY-580).

Support `openjdk` in tag.

Support downloading OpenJDK.

Currently works with Oracle Java 8 and OpenJDK 11.

Add in updated `nss` RPMs

### CODE REVIEW

**Comment by nicdoye** [comment]
Oracle Server JRE 8u181 build https://quay.io/repository/alfresco/alfresco-base-java/manifest/sha256:ffb032d395deb236f4b08081868fe9c488551b9f7bf3674d84e9daf219ee83d6

OpenJDK Java 11 build https://quay.io/repository/alfresco/alfresco-base-java/manifest/sha256:5b832b4bffd95b9ee1c986e01f2f6c2f180b479efc33aaef89186ef415cbaa82

**Comment by nicdoye** [comment]
Build log: https://bamboo.alfresco.com/bamboo/browse/PS-DBJIR2-10

**Comment by nicdoye** [comment]
@rgauss 

My thoughts were that by moving Dockerfile to its own folder (actually [completed](https://github.com/Alfresco/alfresco-docker-base-java/pull/25/files#diff-28b3886804b6c975a958b69b941ea9af) in the previous PR #25), it reduces the size of the build context. Admittedly, this is something of a minor, and usually, pointless optimisation.

I also considered copying the `update.sh` method employed by the official library images. This, I believe would be overkill, when we only have 2 images to build (at the moment). It should be noted that all(?) official library images do not put a single Dockerfile in the root.

I think this is an OK compromise: `ARG`s are visible via `docker inspect`. In this case:

```
docker inspect quay.io/alfresco/alfresco-base-java:11-openjdk-centos-7-DEPLOY-574 | \
  jq '.[].ContainerConfig.Cmd'
```

PS. I certainly hated having the "branch-per-java-version" approach we tried earlier.

**Comment by rgauss** [comment]
> My thoughts were that by moving Dockerfile to its own folder (actually completed in the previous PR #25), it reduces the size of the build context. Admittedly, this is something of a minor, and usually, pointless optimisation.

That might be a good solution if we were taking the approach of different Dockerfiles for different versions, like many projects do, but here it seems more confusing, particularly with the number of folders we now have at the root.  (I must have missed the tiny -> in that other PR or would have mentioned this there)

> It should be noted that all(?) official library images do not put a single Dockerfile in the root.

Right, but most have different Dockerfiles for different versions.

> I certainly hated having the "branch-per-java-version" approach we tried earlier.

The current approach may make it difficult to support 'hot fix' requests against different versions.  It can still be done, and branches aren't the only way to make that easier, but it's something we need to account for.

My bigger concern is that we have **4 directories for script files** and a (unintuitive for some) `src` folder directly under the root of the project making it look more like a linux dir listing than a Dockerfile repo which might slow down developers looking for the Dockerfile.

I'm interested in what others think.  @svidrascu? @jottley? @melahn? (just picking three that might have different perspectives, anyone, please, chime in)

**Comment by melahn** [comment]
Was there a reason we needed to make these other changes to update to Java 11?    

Will these changes make it more difficult or simpler for other teams (APS,ACS...) to consume the new image in time for a Nov EA.   The Repo team also has a goal of producing an ACS 6.1 community image by end of month.

**Comment by nicdoye** [comment]
@melahn Downstream consumers have no need to look at the source repo.

@rgauss I can see your point - it's not exactly hard to move this stuff under `scripts/` and put a `.dockerignore` in.

I think there's little chance we'd need a hot-fix-per-version. #famouslastwords

**Comment by rgauss** [comment]
> I think there's little chance we'd need a hot-fix-per-version

When we upgrade the OS that becomes much more likely.

**Pull request merged**
