### PR TITLE
DEPLOY-483 Medium security issues. Fix shellcheck errors.

### PR DESCRIPTION
**Pull request by nicdoye**
Build is green in Quay https://quay.io/repository/alfresco/alfresco-base-java?tab=tags

### CODE REVIEW

**Comment by nicdoye** [comment]
I'll try a build locally to check.

**Comment by nicdoye** [comment]
I b

Versions included in the new build:
```
nss-3.36.0-5.el7_5.x86_64
bind-license-9.9.4-61.el7.noarch
curl-7.29.0-46.el7.x86_64
systemd-219-57.el7.x86_64
glibc-2.17-222.el7.x86_64
openssl-libs-1.0.2k-12.el7.x86_64
krb5-libs-1.15.1-19.el7.x86_64
libgcc-4.8.5-28.el7_5.1.x86_64
libstdc++-4.8.5-28.el7_5.1.x86_64
```

Versions if I remove the `RUN` line

```
nss-3.28.4-8.el7.x86_64
bind-license-9.9.4-50.el7.noarch
curl-7.29.0-42.el7.x86_64
systemd-219-42.el7.x86_64
glibc-2.17-196.el7.x86_64
openssl-libs-1.0.2k-8.el7.x86_64
krb5-libs-1.15.1-8.el7.x86_64
libgcc-4.8.5-16.el7.x86_64
libstdc++-4.8.5-16.el7.x86_64
```

**Comment by svidrascu** [comment]
Looking good

**Comment by nicdoye** [comment]
OK - @svidrascu was right. I must have messed up my tests above. 😹 

image

**Pull request merged**
