### PR TITLE
Issue#23-Reduce image size by adding 'yum clean all'

### PR DESCRIPTION
**Pull request by sujaypillai**
Updated the Dockerfile by adding 'yum clean all'.

### CODE REVIEW

**Comment by rgauss** [comment]
Apologies for the delay, and thanks for the suggestion.

We'll be taking a closer look at this in the near future.

**Comment by nicdoye** [comment]
Sorry @sujaypillai - I missed this in the latest code merge.

**Comment by nicdoye** [comment]
Tested via DEPLOY-581 build.

**Comment by nicdoye** [comment]
Forgot the obligatory LGTM ;)

**Pull request merged**
